// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfzievfpgkojticgvryn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmemlldmZwZ2tvanRpY2d2cnluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDQ2MjcsImV4cCI6MjA1OTY4MDYyN30.o4tGXSP3oIC6g8dQVk_qKogeUIiMnaJfj5QXO7Qp70g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);